import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Marque from "@/components/Marque";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col container mx-auto">
        <Header></Header>
        <div className="sticky top-0 z-50 bg-white">
          <Marque></Marque>
        </div>
        <main className="container mx-auto max-w-7xl">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
